### ISSUE TITLE
Components as CSS

### ISSUE THREAD

**Issue by qds-soft** [telekom/telements#105]
I'd love to have the components in simple css/scss files for my projects without React/Angular/Vue. Is there a possibility to export the typescript classes to css?

**Comment by tomhoefer** [comment]
Hello :)

Thank you very much for requesting this feature. I think it is definitely worth to have a corresponding basic css file. We will clarify how we can automate this.

@eeegor what do you think?

**Comment by eeegor** [comment]
@qds-soft Hi, thanks for hour question!

You can use the web-components in plain `html` / `vanilla javascript` - so you don't need to use a framework like `React/Angular/Vue`.

Currently we are still in development mode, so you would need to clone and build the library locally if you would like to try it in your projects, but once we are ready for release it will be more convenient and you will be able to get the distributed version from the `npm registry` 

As for just the `css` files - currently we don't have plans to provide those, but can look into it if there is more demand.

Hope this helps!
